// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"
	"database/sql"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (id, user_id, title, mode, response_mode, status, version, created_at, updated_at, metadata_json)
VALUES (?, ?, ?, ?, ?, ?, 1, ?, ?, '{}')
RETURNING id, user_id, title, mode, response_mode, status, version, last_message_at, pinned_at, archived_at, deleted_at, created_at, updated_at
`

type CreateConversationParams struct {
	ID           string
	UserID       string
	Title        string
	Mode         string
	ResponseMode string
	Status       string
	CreatedAt    string
	UpdatedAt    string
}

type CreateConversationRow struct {
	ID            string
	UserID        string
	Title         string
	Mode          string
	ResponseMode  string
	Status        string
	Version       int64
	LastMessageAt sql.NullString
	PinnedAt      sql.NullString
	ArchivedAt    sql.NullString
	DeletedAt     sql.NullString
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (CreateConversationRow, error) {
	row := q.db.QueryRowContext(ctx, createConversation,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Mode,
		arg.ResponseMode,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateConversationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Mode,
		&i.ResponseMode,
		&i.Status,
		&i.Version,
		&i.LastMessageAt,
		&i.PinnedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationForUser = `-- name: GetConversationForUser :one
SELECT id, user_id, title, mode, response_mode, status, version, last_message_at, pinned_at, archived_at, deleted_at, created_at, updated_at
FROM conversations WHERE id = ? AND user_id = ? AND deleted_at IS NULL
`

type GetConversationForUserParams struct {
	ID     string
	UserID string
}

type GetConversationForUserRow struct {
	ID            string
	UserID        string
	Title         string
	Mode          string
	ResponseMode  string
	Status        string
	Version       int64
	LastMessageAt sql.NullString
	PinnedAt      sql.NullString
	ArchivedAt    sql.NullString
	DeletedAt     sql.NullString
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) GetConversationForUser(ctx context.Context, arg GetConversationForUserParams) (GetConversationForUserRow, error) {
	row := q.db.QueryRowContext(ctx, getConversationForUser, arg.ID, arg.UserID)
	var i GetConversationForUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Mode,
		&i.ResponseMode,
		&i.Status,
		&i.Version,
		&i.LastMessageAt,
		&i.PinnedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversationsForUser = `-- name: ListConversationsForUser :many
SELECT id, user_id, title, mode, response_mode, status, version, last_message_at, pinned_at, archived_at, deleted_at, created_at, updated_at
FROM conversations WHERE user_id = ? AND deleted_at IS NULL
ORDER BY updated_at DESC, id DESC LIMIT ? OFFSET ?
`

type ListConversationsForUserParams struct {
	UserID string
	Limit  int64
	Offset int64
}

type ListConversationsForUserRow struct {
	ID            string
	UserID        string
	Title         string
	Mode          string
	ResponseMode  string
	Status        string
	Version       int64
	LastMessageAt sql.NullString
	PinnedAt      sql.NullString
	ArchivedAt    sql.NullString
	DeletedAt     sql.NullString
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) ListConversationsForUser(ctx context.Context, arg ListConversationsForUserParams) ([]ListConversationsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listConversationsForUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsForUserRow
	for rows.Next() {
		var i ListConversationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Mode,
			&i.ResponseMode,
			&i.Status,
			&i.Version,
			&i.LastMessageAt,
			&i.PinnedAt,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConversationArchived = `-- name: SetConversationArchived :one
UPDATE conversations SET archived_at = ?, version = version + 1, updated_at = ?
WHERE id = ? AND user_id = ? AND deleted_at IS NULL
RETURNING id, user_id, title, mode, response_mode, status, version, last_message_at, pinned_at, archived_at, deleted_at, created_at, updated_at
`

type SetConversationArchivedParams struct {
	ArchivedAt sql.NullString
	UpdatedAt  string
	ID         string
	UserID     string
}

type SetConversationArchivedRow struct {
	ID            string
	UserID        string
	Title         string
	Mode          string
	ResponseMode  string
	Status        string
	Version       int64
	LastMessageAt sql.NullString
	PinnedAt      sql.NullString
	ArchivedAt    sql.NullString
	DeletedAt     sql.NullString
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) SetConversationArchived(ctx context.Context, arg SetConversationArchivedParams) (SetConversationArchivedRow, error) {
	row := q.db.QueryRowContext(ctx, setConversationArchived,
		arg.ArchivedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	var i SetConversationArchivedRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Mode,
		&i.ResponseMode,
		&i.Status,
		&i.Version,
		&i.LastMessageAt,
		&i.PinnedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteConversation = `-- name: SoftDeleteConversation :execrows
UPDATE conversations SET deleted_at = ?, version = version + 1, updated_at = ?
WHERE id = ? AND user_id = ? AND deleted_at IS NULL
`

type SoftDeleteConversationParams struct {
	DeletedAt sql.NullString
	UpdatedAt string
	ID        string
	UserID    string
}

func (q *Queries) SoftDeleteConversation(ctx context.Context, arg SoftDeleteConversationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteConversation,
		arg.DeletedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateConversationVersion = `-- name: UpdateConversationVersion :one
UPDATE conversations SET title = ?, mode = ?, response_mode = ?, version = version + 1, updated_at = ?
WHERE id = ? AND user_id = ? AND version = ? AND deleted_at IS NULL
RETURNING id, user_id, title, mode, response_mode, status, version, last_message_at, pinned_at, archived_at, deleted_at, created_at, updated_at
`

type UpdateConversationVersionParams struct {
	Title        string
	Mode         string
	ResponseMode string
	UpdatedAt    string
	ID           string
	UserID       string
	Version      int64
}

type UpdateConversationVersionRow struct {
	ID            string
	UserID        string
	Title         string
	Mode          string
	ResponseMode  string
	Status        string
	Version       int64
	LastMessageAt sql.NullString
	PinnedAt      sql.NullString
	ArchivedAt    sql.NullString
	DeletedAt     sql.NullString
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) UpdateConversationVersion(ctx context.Context, arg UpdateConversationVersionParams) (UpdateConversationVersionRow, error) {
	row := q.db.QueryRowContext(ctx, updateConversationVersion,
		arg.Title,
		arg.Mode,
		arg.ResponseMode,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
		arg.Version,
	)
	var i UpdateConversationVersionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Mode,
		&i.ResponseMode,
		&i.Status,
		&i.Version,
		&i.LastMessageAt,
		&i.PinnedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
