// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (id, conversation_id, run_id, invocation_id, event_type, payload, sequence, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, conversation_id, run_id, invocation_id, event_type, payload, sequence, created_at
`

type CreateEventParams struct {
	ID             string
	ConversationID string
	RunID          string
	InvocationID   string
	EventType      string
	Payload        string
	Sequence       int64
	CreatedAt      string
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.ID,
		arg.ConversationID,
		arg.RunID,
		arg.InvocationID,
		arg.EventType,
		arg.Payload,
		arg.Sequence,
		arg.CreatedAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.RunID,
		&i.InvocationID,
		&i.EventType,
		&i.Payload,
		&i.Sequence,
		&i.CreatedAt,
	)
	return i, err
}

const listEventsAfter = `-- name: ListEventsAfter :many
SELECT id, conversation_id, run_id, invocation_id, event_type, payload, sequence, created_at
FROM events WHERE run_id = ? AND sequence > ? ORDER BY sequence ASC LIMIT ?
`

type ListEventsAfterParams struct {
	RunID    string
	Sequence int64
	Limit    int64
}

func (q *Queries) ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsAfter, arg.RunID, arg.Sequence, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.RunID,
			&i.InvocationID,
			&i.EventType,
			&i.Payload,
			&i.Sequence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextEventSequence = `-- name: NextEventSequence :one
SELECT COALESCE(MAX(sequence), 0) + 1 FROM events WHERE run_id = ?
`

func (q *Queries) NextEventSequence(ctx context.Context, runID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextEventSequence, runID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
