// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"
	"database/sql"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, conversation_id, run_id, message_id, role, sender_type, content, content_json, reply_to_message_id, status, created_at, updated_at, metadata_json, client_message_id, sequence)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '{}', ?, ?)
RETURNING id, conversation_id, run_id, client_message_id, sender_type, content, content_json, reply_to_message_id, status, sequence, created_at, updated_at, deleted_at
`

type CreateMessageParams struct {
	ID               string
	ConversationID   string
	RunID            sql.NullString
	MessageID        string
	Role             string
	SenderType       string
	Content          string
	ContentJson      sql.NullString
	ReplyToMessageID sql.NullString
	Status           string
	CreatedAt        string
	UpdatedAt        string
	ClientMessageID  sql.NullString
	Sequence         int64
}

type CreateMessageRow struct {
	ID               string
	ConversationID   string
	RunID            sql.NullString
	ClientMessageID  sql.NullString
	SenderType       string
	Content          string
	ContentJson      sql.NullString
	ReplyToMessageID sql.NullString
	Status           string
	Sequence         int64
	CreatedAt        string
	UpdatedAt        string
	DeletedAt        sql.NullString
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ID,
		arg.ConversationID,
		arg.RunID,
		arg.MessageID,
		arg.Role,
		arg.SenderType,
		arg.Content,
		arg.ContentJson,
		arg.ReplyToMessageID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ClientMessageID,
		arg.Sequence,
	)
	var i CreateMessageRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.RunID,
		&i.ClientMessageID,
		&i.SenderType,
		&i.Content,
		&i.ContentJson,
		&i.ReplyToMessageID,
		&i.Status,
		&i.Sequence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMessageByClientID = `-- name: GetMessageByClientID :one
SELECT id, conversation_id, run_id, client_message_id, sender_type, content, content_json, reply_to_message_id, status, sequence, created_at, updated_at, deleted_at
FROM messages WHERE conversation_id = ? AND client_message_id = ? AND deleted_at IS NULL
`

type GetMessageByClientIDParams struct {
	ConversationID  string
	ClientMessageID sql.NullString
}

type GetMessageByClientIDRow struct {
	ID               string
	ConversationID   string
	RunID            sql.NullString
	ClientMessageID  sql.NullString
	SenderType       string
	Content          string
	ContentJson      sql.NullString
	ReplyToMessageID sql.NullString
	Status           string
	Sequence         int64
	CreatedAt        string
	UpdatedAt        string
	DeletedAt        sql.NullString
}

func (q *Queries) GetMessageByClientID(ctx context.Context, arg GetMessageByClientIDParams) (GetMessageByClientIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMessageByClientID, arg.ConversationID, arg.ClientMessageID)
	var i GetMessageByClientIDRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.RunID,
		&i.ClientMessageID,
		&i.SenderType,
		&i.Content,
		&i.ContentJson,
		&i.ReplyToMessageID,
		&i.Status,
		&i.Sequence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, run_id, client_message_id, sender_type, content, content_json, reply_to_message_id, status, sequence, created_at, updated_at, deleted_at
FROM messages WHERE conversation_id = ? AND deleted_at IS NULL ORDER BY sequence ASC, id ASC LIMIT ? OFFSET ?
`

type ListMessagesParams struct {
	ConversationID string
	Limit          int64
	Offset         int64
}

type ListMessagesRow struct {
	ID               string
	ConversationID   string
	RunID            sql.NullString
	ClientMessageID  sql.NullString
	SenderType       string
	Content          string
	ContentJson      sql.NullString
	ReplyToMessageID sql.NullString
	Status           string
	Sequence         int64
	CreatedAt        string
	UpdatedAt        string
	DeletedAt        sql.NullString
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessages, arg.ConversationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesRow
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.RunID,
			&i.ClientMessageID,
			&i.SenderType,
			&i.Content,
			&i.ContentJson,
			&i.ReplyToMessageID,
			&i.Status,
			&i.Sequence,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextMessageSequence = `-- name: NextMessageSequence :one
SELECT COALESCE(MAX(sequence), 0) + 1 FROM messages WHERE conversation_id = ?
`

func (q *Queries) NextMessageSequence(ctx context.Context, conversationID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextMessageSequence, conversationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const softDeleteMessage = `-- name: SoftDeleteMessage :execrows
UPDATE messages SET deleted_at = ?, updated_at = ? WHERE id = ? AND conversation_id = ? AND deleted_at IS NULL
`

type SoftDeleteMessageParams struct {
	DeletedAt      sql.NullString
	UpdatedAt      string
	ID             string
	ConversationID string
}

func (q *Queries) SoftDeleteMessage(ctx context.Context, arg SoftDeleteMessageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteMessage,
		arg.DeletedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.ConversationID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateMessageContentStatus = `-- name: UpdateMessageContentStatus :execrows
UPDATE messages SET content = ?, status = ?, error_code = ?, error_message = ?, updated_at = ? WHERE id = ?
`

type UpdateMessageContentStatusParams struct {
	Content      string
	Status       string
	ErrorCode    string
	ErrorMessage string
	UpdatedAt    string
	ID           string
}

func (q *Queries) UpdateMessageContentStatus(ctx context.Context, arg UpdateMessageContentStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMessageContentStatus,
		arg.Content,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
