// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Artifact struct {
	ID             string
	ConversationID string
	RunID          sql.NullString
	StepID         sql.NullString
	MessageID      sql.NullString
	ArtifactType   string
	Title          string
	MimeType       string
	PreviewType    string
	ContentRef     string
	Status         string
	CreatedAt      string
	UpdatedAt      string
	MetadataJson   string
}

type Conversation struct {
	ID            string
	Title         string
	Status        string
	CreatedAt     string
	UpdatedAt     string
	MetadataJson  string
	Pinned        int64
	PinnedAt      sql.NullString
	UserID        string
	Mode          string
	ResponseMode  string
	Version       int64
	LastMessageAt sql.NullString
	ArchivedAt    sql.NullString
	DeletedAt     sql.NullString
}

type ConversationParticipant struct {
	ID              string
	ConversationID  string
	ParticipantType string
	ParticipantName string
	DisplayName     string
	CreatedAt       string
	MetadataJson    string
}

type Event struct {
	ID             string
	ConversationID string
	RunID          string
	InvocationID   string
	EventType      string
	Payload        string
	Sequence       int64
	CreatedAt      string
}

type Message struct {
	ID               string
	ConversationID   string
	RunID            sql.NullString
	StepID           sql.NullString
	MessageID        string
	Role             string
	SenderType       string
	SenderName       string
	AgentName        string
	Content          string
	Status           string
	ErrorCode        string
	ErrorMessage     string
	CreatedAt        string
	UpdatedAt        string
	MetadataJson     string
	ClientMessageID  sql.NullString
	ReplyToMessageID sql.NullString
	ContentJson      sql.NullString
	Sequence         int64
	DeletedAt        sql.NullString
}

type Run struct {
	ID                   string
	ConversationID       string
	Status               string
	PlanningMode         string
	StartedAt            string
	FinishedAt           sql.NullString
	ErrorCode            string
	ErrorMessage         string
	MetadataJson         string
	TriggerMessageID     sql.NullString
	Mode                 string
	PlanID               sql.NullString
	ConfirmedPlanVersion sql.NullString
	ContextSnapshotID    sql.NullString
	UpdatedAt            sql.NullString
	CreatedAt            sql.NullString
}

type RunStep struct {
	ID             string
	RunID          string
	ConversationID string
	TaskID         string
	StepIndex      int64
	AgentName      string
	CapabilityID   string
	Status         string
	StartedAt      sql.NullString
	FinishedAt     sql.NullString
	ErrorCode      string
	ErrorMessage   string
	MetadataJson   string
}
