// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: run_steps.sql

package db

import (
	"context"
	"database/sql"
)

const createRunStep = `-- name: CreateRunStep :exec
INSERT INTO run_steps (id, run_id, conversation_id, task_id, step_index, agent_name, capability_id, status, started_at, metadata_json)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, '{}')
`

type CreateRunStepParams struct {
	ID             string
	RunID          string
	ConversationID string
	TaskID         string
	StepIndex      int64
	AgentName      string
	CapabilityID   string
	Status         string
	StartedAt      sql.NullString
}

func (q *Queries) CreateRunStep(ctx context.Context, arg CreateRunStepParams) error {
	_, err := q.db.ExecContext(ctx, createRunStep,
		arg.ID,
		arg.RunID,
		arg.ConversationID,
		arg.TaskID,
		arg.StepIndex,
		arg.AgentName,
		arg.CapabilityID,
		arg.Status,
		arg.StartedAt,
	)
	return err
}

const updateRunStepStatus = `-- name: UpdateRunStepStatus :execrows
UPDATE run_steps SET status = ?, error_code = ?, error_message = ?, finished_at = ? WHERE id = ?
`

type UpdateRunStepStatusParams struct {
	Status       string
	ErrorCode    string
	ErrorMessage string
	FinishedAt   sql.NullString
	ID           string
}

func (q *Queries) UpdateRunStepStatus(ctx context.Context, arg UpdateRunStepStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRunStepStatus,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.FinishedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
