// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package db

import (
	"context"
	"database/sql"
)

const compareAndSetRunStatus = `-- name: CompareAndSetRunStatus :execrows
UPDATE runs SET status = ?, finished_at = ?, updated_at = ? WHERE id = ? AND status = ?
`

type CompareAndSetRunStatusParams struct {
	Status     string
	FinishedAt sql.NullString
	UpdatedAt  sql.NullString
	ID         string
	Status_2   string
}

func (q *Queries) CompareAndSetRunStatus(ctx context.Context, arg CompareAndSetRunStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, compareAndSetRunStatus,
		arg.Status,
		arg.FinishedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.Status_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (id, conversation_id, trigger_message_id, mode, status, plan_id, confirmed_plan_version, context_snapshot_id, started_at, error_code, metadata_json, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, '', '{}', ?)
RETURNING id, conversation_id, trigger_message_id, mode, status, plan_id, confirmed_plan_version, context_snapshot_id, started_at, finished_at, error_code, metadata_json, created_at, updated_at
`

type CreateRunParams struct {
	ID                   string
	ConversationID       string
	TriggerMessageID     sql.NullString
	Mode                 string
	Status               string
	PlanID               sql.NullString
	ConfirmedPlanVersion sql.NullString
	ContextSnapshotID    sql.NullString
	StartedAt            string
	UpdatedAt            sql.NullString
}

type CreateRunRow struct {
	ID                   string
	ConversationID       string
	TriggerMessageID     sql.NullString
	Mode                 string
	Status               string
	PlanID               sql.NullString
	ConfirmedPlanVersion sql.NullString
	ContextSnapshotID    sql.NullString
	StartedAt            string
	FinishedAt           sql.NullString
	ErrorCode            string
	MetadataJson         string
	CreatedAt            sql.NullString
	UpdatedAt            sql.NullString
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (CreateRunRow, error) {
	row := q.db.QueryRowContext(ctx, createRun,
		arg.ID,
		arg.ConversationID,
		arg.TriggerMessageID,
		arg.Mode,
		arg.Status,
		arg.PlanID,
		arg.ConfirmedPlanVersion,
		arg.ContextSnapshotID,
		arg.StartedAt,
		arg.UpdatedAt,
	)
	var i CreateRunRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.TriggerMessageID,
		&i.Mode,
		&i.Status,
		&i.PlanID,
		&i.ConfirmedPlanVersion,
		&i.ContextSnapshotID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorCode,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, conversation_id, trigger_message_id, mode, status, plan_id, confirmed_plan_version, context_snapshot_id, started_at, finished_at, error_code, metadata_json, created_at, updated_at FROM runs WHERE id = ?
`

type GetRunRow struct {
	ID                   string
	ConversationID       string
	TriggerMessageID     sql.NullString
	Mode                 string
	Status               string
	PlanID               sql.NullString
	ConfirmedPlanVersion sql.NullString
	ContextSnapshotID    sql.NullString
	StartedAt            string
	FinishedAt           sql.NullString
	ErrorCode            string
	MetadataJson         string
	CreatedAt            sql.NullString
	UpdatedAt            sql.NullString
}

func (q *Queries) GetRun(ctx context.Context, id string) (GetRunRow, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i GetRunRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.TriggerMessageID,
		&i.Mode,
		&i.Status,
		&i.PlanID,
		&i.ConfirmedPlanVersion,
		&i.ContextSnapshotID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorCode,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRunsByConversation = `-- name: ListRunsByConversation :many
SELECT id, conversation_id, trigger_message_id, mode, status, plan_id, confirmed_plan_version, context_snapshot_id, started_at, finished_at, error_code, metadata_json, created_at, updated_at FROM runs WHERE conversation_id = ? ORDER BY started_at DESC, id DESC LIMIT ? OFFSET ?
`

type ListRunsByConversationParams struct {
	ConversationID string
	Limit          int64
	Offset         int64
}

type ListRunsByConversationRow struct {
	ID                   string
	ConversationID       string
	TriggerMessageID     sql.NullString
	Mode                 string
	Status               string
	PlanID               sql.NullString
	ConfirmedPlanVersion sql.NullString
	ContextSnapshotID    sql.NullString
	StartedAt            string
	FinishedAt           sql.NullString
	ErrorCode            string
	MetadataJson         string
	CreatedAt            sql.NullString
	UpdatedAt            sql.NullString
}

func (q *Queries) ListRunsByConversation(ctx context.Context, arg ListRunsByConversationParams) ([]ListRunsByConversationRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunsByConversation, arg.ConversationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunsByConversationRow
	for rows.Next() {
		var i ListRunsByConversationRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.TriggerMessageID,
			&i.Mode,
			&i.Status,
			&i.PlanID,
			&i.ConfirmedPlanVersion,
			&i.ContextSnapshotID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ErrorCode,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
